run:
  timeout: 5m


linters:
  enable:
    - deadcode
    - gosec
    - gocyclo
    - revive
    - staticcheck
  disable:
    - go-critic

linters-settings:
  gosec:
    severity: "medium"
  gocyclo:
    min-complexity: 10
  revive:
    errorCode: 1
