version: 2.1

jobs:
  lint:
    docker:
      - image: golang:1.22
    steps:
      - checkout
      - run:
          name: Install GolangCI-Lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.47.3
      - run:
          name: Add GolangCI-Lint to PATH
          command: echo 'export PATH=$(go env GOPATH)/bin:$PATH' >> $BASH_ENV
      - run:
          name: Download Dependencies
          command: go mod download
      - run:
          name: Run GolangCI-Lint
          command: golangci-lint run
      - run:
          name: Run Tests
          command: go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
