version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install GolangCI-Lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
      - run:
          name: Run GolangCI-Lint
          command: golangci-lint run
      - run:
          name: Run Tests
          command: go test ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint

